### ISSUE TITLE
对于目前在PySide6.4.2版本以上最大化视窗时右侧与下方边界超出的临时解决方案

### ISSUE THREAD

**Issue by 27161433** [zhiyiYo/PyQt-Frameless-Window#121] opened 2023-08-21 06:32 UTC
我尝试使用重写width与height函数的方法来使视窗最大化时width与height数值回到正确的数值
修改的文件是`./windows/__init__.py`

**修改前**
![image](https://github.com/zhiyiYo/PyQt-Frameless-Window/assets/57839436/944bb102-a1f9-4bc2-9e7f-cf9175c19294)

**修改後**
![image](https://github.com/zhiyiYo/PyQt-Frameless-Window/assets/57839436/a202a2d9-6247-4a80-9a30-7e92d095f87b)

**具体修改如下**
```python
from pkg_resources import parse_version
import PySide6

class WindowsFramelessWindowBase:
    ...
    def nativeEvent(self, eventType, message):
        ...
        if msg.message == win32con.WM_NCHITTEST and self._isResizeEnabled:
            pos = QCursor.pos()
            xPos = pos.x() - self.x()
            yPos = pos.y() - self.y()
            w, h = self.width(), self.height()

            if self.isMaximized():
                _ty = win_utils.getResizeBorderThickness(msg.hWnd, False)
                _tx = win_utils.getResizeBorderThickness(msg.hWnd, True)

                w, h = self.width() + _tx * 2, self.height() + _ty * 2
        ...

class WindowsFramelessWindow(QWidget, WindowsFramelessWindowBase):
    ...
    def width(self):
        if self.isMaximized() and parse_version(installed_version) > parse_version("6.4.2"):
            tx = win_utils.getResizeBorderThickness(self.winId(), True)
            return self.geometry().width() - tx * 2
        else:
            return self.geometry().width()

    def height(self):
        if self.isMaximized() and parse_version(installed_version) > parse_version("6.4.2"):
            ty = win_utils.getResizeBorderThickness(self.winId(), False)
            return self.geometry().height() - ty * 2
        else:
            return self.geometry().height()
```

**完整代碼**
```python
# coding:utf-8
from ctypes import cast
from ctypes.wintypes import LPRECT, MSG
from pkg_resources import parse_version
import PySide6
import win32con
import win32gui
from PySide6.QtCore import Qt
from PySide6.QtGui import QCloseEvent, QCursor
from PySide6.QtWidgets import QApplication, QDialog, QWidget, QMainWindow

from ..titlebar import TitleBar
from ..utils import win32_utils as win_utils
from ..utils.win32_utils import Taskbar
from .c_structures import LPNCCALCSIZE_PARAMS, MINMAXINFO
from .window_effect import WindowsWindowEffect

installed_version = PySide6.__version__

class WindowsFramelessWindowBase:
    """ Frameless window base class for Windows system """

    BORDER_WIDTH = 5

    def __init__(self, *args, **kwargs):
        pass

    def _initFrameless(self):
        self.windowEffect = WindowsWindowEffect(self)
        self.titleBar = TitleBar(self)
        self._isResizeEnabled = True

        # remove window border
        if not win_utils.isWin7():
            self.setWindowFlags(self.windowFlags() | Qt.FramelessWindowHint)
        else:
            self.setWindowFlags(Qt.FramelessWindowHint |
                                Qt.WindowMinMaxButtonsHint)

        # add DWM shadow and window animation
        self.windowEffect.addWindowAnimation(self.winId())
        if not isinstance(self, AcrylicWindow):
            self.windowEffect.addShadowEffect(self.winId())

        # solve issue #5
        self.windowHandle().screenChanged.connect(self.__onScreenChanged)

        self.resize(500, 500)
        self.titleBar.raise_()

    def setTitleBar(self, titleBar):
        """ set custom title bar

        Parameters
        ----------
        titleBar: TitleBar
            title bar
        """
        self.titleBar.deleteLater()
        self.titleBar = titleBar
        self.titleBar.setParent(self)
        self.titleBar.raise_()

    def setResizeEnabled(self, isEnabled: bool):
        """ set whether resizing is enabled """
        self._isResizeEnabled = isEnabled

    def nativeEvent(self, eventType, message):
        """ Handle the Windows message """
        msg = MSG.from_address(message.__int__())
        if not msg.hWnd:
            return False, 0

        if msg.message == win32con.WM_NCHITTEST and self._isResizeEnabled:
            pos = QCursor.pos()
            xPos = pos.x() - self.x()
            yPos = pos.y() - self.y()
            w, h = self.width(), self.height()

            if self.isMaximized():
                _ty = win_utils.getResizeBorderThickness(msg.hWnd, False)
                _tx = win_utils.getResizeBorderThickness(msg.hWnd, True)

                w, h = self.width() + _tx * 2, self.height() + _ty * 2

            # fixes https://github.com/zhiyiYo/PyQt-Frameless-Window/issues/98
            bw = 0 if win_utils.isMaximized(msg.hWnd) or win_utils.isFullScreen(msg.hWnd) else self.BORDER_WIDTH
            lx = xPos < bw
            rx = xPos > w - bw
            ty = yPos < bw
            by = yPos > h - bw
            if lx and ty:
                return True, win32con.HTTOPLEFT
            elif rx and by:
                return True, win32con.HTBOTTOMRIGHT
            elif rx and ty:
                return True, win32con.HTTOPRIGHT
            elif lx and by:
                return True, win32con.HTBOTTOMLEFT
            elif ty:
                return True, win32con.HTTOP
            elif by:
                return True, win32con.HTBOTTOM
            elif lx:
                return True, win32con.HTLEFT
            elif rx:
                return True, win32con.HTRIGHT
        elif msg.message == win32con.WM_NCCALCSIZE:
            if msg.wParam:
                rect = cast(msg.lParam, LPNCCALCSIZE_PARAMS).contents.rgrc[0]
            else:
                rect = cast(msg.lParam, LPRECT).contents

            isMax = win_utils.isMaximized(msg.hWnd)
            isFull = win_utils.isFullScreen(msg.hWnd)

            # adjust the size of client rect
            if isMax and not isFull:
                ty = win_utils.getResizeBorderThickness(msg.hWnd, False)
                rect.top += ty
                rect.bottom -= ty

                tx = win_utils.getResizeBorderThickness(msg.hWnd, True)
                rect.left += tx
                rect.right -= tx

            # handle the situation that an auto-hide taskbar is enabled
            if (isMax or isFull) and Taskbar.isAutoHide():
                position = Taskbar.getPosition(msg.hWnd)
                if position == Taskbar.LEFT:
                    rect.top += Taskbar.AUTO_HIDE_THICKNESS
                elif position == Taskbar.BOTTOM:
                    rect.bottom -= Taskbar.AUTO_HIDE_THICKNESS
                elif position == Taskbar.LEFT:
                    rect.left += Taskbar.AUTO_HIDE_THICKNESS
                elif position == Taskbar.RIGHT:
                    rect.right -= Taskbar.AUTO_HIDE_THICKNESS

            result = 0 if not msg.wParam else win32con.WVR_REDRAW
            return True, result

        return False, 0

    def __onScreenChanged(self):
        hWnd = int(self.windowHandle().winId())
        win32gui.SetWindowPos(hWnd, None, 0, 0, 0, 0, win32con.SWP_NOMOVE |
                              win32con.SWP_NOSIZE | win32con.SWP_FRAMECHANGED)

    def resizeEvent(self, e):
        self.titleBar.resize(self.width(), self.titleBar.height())


class WindowsFramelessWindow(QWidget, WindowsFramelessWindowBase):
    """  Frameless window for Windows system """

    def __init__(self, parent=None):
        super().__init__(parent=parent)
        self._initFrameless()

    def resizeEvent(self, e):
        WindowsFramelessWindowBase.resizeEvent(self, e)

    def nativeEvent(self, eventType, message):
        return WindowsFramelessWindowBase.nativeEvent(self, eventType, message)

    def width(self):
        if self.isMaximized() and parse_version(installed_version) > parse_version("6.4.2"):
            tx = win_utils.getResizeBorderThickness(self.winId(), True)
            return self.geometry().width() - tx * 2
        else:
            return self.geometry().width()

    def height(self):
        if self.isMaximized() and parse_version(installed_version) > parse_version("6.4.2"):
            ty = win_utils.getResizeBorderThickness(self.winId(), False)
            return self.geometry().height() - ty * 2
        else:
            return self.geometry().height()

class AcrylicWindow(WindowsFramelessWindow):
    """ A frameless window with acrylic effect """

    def __init__(self, parent=None):
        super().__init__(parent=parent)
        self.__closedByKey = False

    def _initFrameless(self):
        super()._initFrameless()
        self.setWindowFlags(Qt.FramelessWindowHint)
        self.windowEffect.enableBlurBehindWindow(self.winId())
        self.windowEffect.addWindowAnimation(self.winId())

        if win_utils.isWin7():
            self.windowEffect.addShadowEffect(self.winId())
            self.windowEffect.setAeroEffect(self.winId())
        else:
            self.windowEffect.setAcrylicEffect(self.winId())
            if win_utils.isGreaterEqualWin11():
                self.windowEffect.addShadowEffect(self.winId())

        self.setStyleSheet("AcrylicWindow{background:transparent}")

    def nativeEvent(self, eventType, message):
        """ Handle the Windows message """
        msg = MSG.from_address(message.__int__())

        # handle Alt+F4
        if msg.message == win32con.WM_SYSKEYDOWN:
            if msg.wParam == win32con.VK_F4:
                self.__closedByKey = True
                QApplication.sendEvent(self, QCloseEvent())
                return False, 0

        return super().nativeEvent(eventType, message)

    def closeEvent(self, e):
        if not self.__closedByKey or QApplication.quitOnLastWindowClosed():
            self.__closedByKey = False
            return super().closeEvent(e)

        # system tray icon
        self.__closedByKey = False
        self.hide()


class WindowsFramelessMainWindow(QMainWindow, WindowsFramelessWindowBase):
    """ Frameless main window for Windows system """

    def __init__(self, parent=None):
        super().__init__(parent=parent)
        self._initFrameless()

    def resizeEvent(self, e):
        QMainWindow.resizeEvent(self, e)
        self.titleBar.resize(self.width(), self.titleBar.height())

    def nativeEvent(self, eventType, message):
        return WindowsFramelessWindowBase.nativeEvent(self, eventType, message)


class WindowsFramelessDialog(QDialog, WindowsFramelessWindowBase):
    """ Frameless dialog for Windows system """

    def __init__(self, parent=None):
        super().__init__(parent=parent)
        self._initFrameless()
        self.titleBar.minBtn.hide()
        self.titleBar.maxBtn.hide()
        self.titleBar.setDoubleClickEnabled(False)
        self.windowEffect.disableMaximizeButton(self.winId())

    def resizeEvent(self, e):
        WindowsFramelessWindowBase.resizeEvent(self, e)

    def nativeEvent(self, eventType, message):
        return WindowsFramelessWindowBase.nativeEvent(self, eventType, message)
```

**Comment by xMesa-git** [comment] 2023-10-20 10:09
please merge this fix

**Comment by zhiyiYo** [comment] 2023-10-25 05:20
这个方法还是有点问题，在 1920 * 1080 且缩放比为 125% 的屏幕上右侧会有一部分空出来：
![image](https://github.com/zhiyiYo/PyQt-Frameless-Window/assets/65096819/8c220813-5383-461a-a194-8e39988c6045)

**Comment by UsYer** [comment] 2023-11-20 16:12
I'm having the same problem on QT 6.6. Is there any chance this could be fixed here in the package itself?

**Comment by AlexZhu2001** [comment] 2023-12-21 14:43
这个问题是Qt本身的bug，来源于一些优化。
Qt6.4.3开始，在QPA中的QWindowsWindow计算Margins将会忽略设置了FramelessWindowHint的窗口的Margins，在最大化后由于窗口实际的大小是大于可绘制的区域的，但是由于跳过了Margins的计算导致应当被扣除的margins没有计算。
具体的BUG已经反馈给Qt了，见[QTBUG-120196](https://bugreports.qt.io/browse/QTBUG-120196)，patch也已提交，目前dev分支已经完成了merge，等cherrypick到历史版本，下一次PyQt更新的时候可能就能修复了

**Comment by zhiyiYo** [comment] 2023-12-21 15:53
> 这个问题是Qt本身的bug，来源于一些优化。 Qt6.4.3开始，在QPA中的QWindowsWindow计算Margins将会忽略设置了FramelessWindowHint的窗口的Margins，在最大化后由于窗口实际的大小是大于可绘制的区域的，但是由于跳过了Margins的计算导致应当被扣除的margins没有计算。 具体的BUG已经反馈给Qt了，见[QTBUG-120196](https://bugreports.qt.io/browse/QTBUG-120196)，patch也已提交，目前dev分支已经完成了merge，等cherrypick到历史版本，下一次PySide更新的时候可能就能修复了 [Patch 地址](https://codereview.qt-project.org/c/qt/qtbase/+/527045)

给力

**Comment by msalmonw** [comment] 2024-02-15 08:34
> This issue is a bug in Qt itself, due to some optimizations. Starting from Qt6.4.3, the QWindowsWindow calculation margins in QPA will ignore the margins of the window with FramelessWindowHint set, after maximization, because the actual size of the window is larger than the drawable area, but the margins that should be deducted are not calculated because the calculation of margins is skipped. The specific BUG has been fed back to Qt, see [QTBUG-120196](https://bugreports.qt.io/browse/QTBUG-120196), the patch has also been submitted, the dev branch has completed the merge, wait for cherrypick to the historical version, and the [patch address](https://codereview.qt-project.org/c/qt/qtbase/+/527045) may be fixed when the next PySide update is made

I updated to the latest pyside6.6 but the issue still persists. Though the bugfix has been merged in the 6.6 branch. Am I missing something here?

**Comment by zhiyiYo** [comment] 2024-02-15 09:20
@msalmonw PySide 6.6.2 has not yet fixed this issue

**Comment by msalmonw** [comment] 2024-02-15 09:28
weird, then why does cherry pick say the fix has been merged in 6.7/6/5

**Comment by UsYer** [comment] 2024-02-17 10:20
For me, the issue is indeed fixed with PySide6 6.6.2. 
I suggest just to try if it works now,

**Comment by msalmonw** [comment] 2024-02-17 10:21
okay i'll check. thanks!

**Comment by zhiyiYo** [comment] 2024-02-17 11:00
PySide6.6.2 has fixed this issue

**Closed by zhiyiYo** 2024-02-17 11:00 UTC
Labels: enhancement
